ci.yml: changes
d0k3/GodMode9 pull request #674
Opened 2021-02-15 07:43 UTC by Margen67

2021-02-16 02:56 UTC, aspargas2 commented
One problem with this: because the devkitarm docker image comes with an older version of git (or at least I think that's why), checkout v2 can't properly clone the repo and instead does it with github's rest API, which leaves out the entire .git folder. This in turn prevents gm9's Makefile from having any information on what commit is being built, so the resulting build artifact will be missing everything derived from that (this can be seen in the artifact produced by the CI build run on this pull request). 

Other than that, these changes are fine. I would recommend simply leaving it using checkout v1, as I do no know of any downside to doing so.

2021-02-19 11:27 UTC, d0k3 requested changes
One small change needed, then we can merge this.

2021-02-19 11:27 UTC, d0k3 commented on .github/workflows/ci.yml
> -      - uses: actions/checkout@v1
Leave this at checkout v1 - this will make things easier for us. See @aspargas2's comment.

2021-03-01 09:29 UTC, Margen67 commented
> One problem with this: because the devkitarm docker image comes with an older version of git (or at least I think that's why), checkout v2 can't properly clone the repo and instead does it with github's rest API, which leaves out the entire .git folder. This in turn prevents gm9's Makefile from having any information on what commit is being built, so the resulting build artifact will be missing everything derived from that (this can be seen in the artifact produced by the CI build run on this pull request).
> 
> Other than that, these changes are fine. I would recommend simply leaving it using checkout v1, as I do no know of any downside to doing so.

@aspargas2 Checkout v2 does a [shallow clone by default](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches):
```
# Number of commits to fetch. 0 indicates all history for all branches and tags.
# Default: 1
fetch-depth: ''
```

2021-03-12 13:57 UTC, Margen67 commented
> 
> 
> One small change needed, then we can merge this.

@d0k3 Fixed.

2021-03-14 13:58 UTC, d0k3 approved these changes
Looks good to me!

2021-03-14 13:59 UTC, merged