Preserve RSA keys in trimmed NDS dumps
d0k3/GodMode9 pull request #722
Opened 2021-07-16 09:42 UTC by lifehackerhansol

Fixes #721, implemented exactly as described in the issue.

This was tested on a Mario Kart DS (Korea) cartridge, while being played on nds-bootstrap and an original R4, where cloneboot requires the RSA key. It is useful for real hardware NDS playback as a whole.

I unfortunately do not have a TWL cart to test the fix there. If anyone else is willing to test, or have any suggestions about what to add to this PR, feel free to let me know or directly commit.

2021-07-16 09:46 UTC, lifehackerhansol commented
Force push was to change the author email. Nothing else changed.

2021-07-16 10:20 UTC, lifehackerhansol commented
There have been some points brought up mid-testing with some members in the community as to whether it is actually worthwhile to keep the appended 0x88 in TWL carts. There isn't a known TWL cart (as in DSi Enhanced or DSi Exclusive) that utilizes cloneboot at all, so it may just be unneeded extra data which goes against the purpose of trim dumps.

In GodMode9i, where this was first implemented (mentioned in the related issue), I don't think there is a particular check for NTR or TWL dumps. In my opinion if it'll be done on one cart it should be done for all, but I think it's better for someone else to decide this.

2021-07-16 13:08 UTC, SNBeast commented
There is a check for NTR vs. TWL dumps in GodMode9i, and it's in the code snippet in the linked issue above: `ndsCardHeader.unitCode != 0`. The unit code is 0 for NTR, 2 for TWL with NTR support, and 3 for TWL only.

2021-07-16 13:44 UTC, lifehackerhansol commented
I see, so the check only applies when the unit code is 0, then? I may have misunderstood the code the first time I saw.

2021-07-16 13:53 UTC, SNBeast commented
Yes. `+` has a higher operator precedence than `?` and `:`, so the choices read "`ndsCardHeader.twlRomSize` if true, `ndsCardHeader.romSize + 0x88` if false."

2021-07-16 14:13 UTC, lifehackerhansol commented
Yeah not sure how I messed that up. It's gone now.

2021-07-23 15:33 UTC, lifehackerhansol commented
At the moment, this commit freezes GodMode9, though it is implemented as described in the issue. I'll try again.

2021-07-23 16:39 UTC, d0k3 commented
Should not freeze GM9. Make sure you've got the latest master as base. Also take note that appending + 0x88 to that exact location is what I did earlier. According to @SNBeast this is not correct.

2021-07-23 16:49 UTC, lifehackerhansol commented
> Should not freeze GM9. Make sure you've got the latest master as base. Also take note that appending + 0x88 to that exact location is what I did earlier. According to @SNBeast this is not correct.

Apparently, it doesn't work when reading from C: GAMECART. It does however, preserve the key on an existing ROM on the SD.

2021-07-24 19:51 UTC, d0k3 commented
Alright, I forgot about that one actually, that's a different place in the code. Maybe your initial fix wasn't so bad. You need to make sure, tough, that the data size never exceeds the cart size.

2021-08-04 15:51 UTC, d0k3 commented
Don't want to bother, but do you by any chance have a new build that can be tested? Sorry about the earlier confusion, your initial fix was actually the correct way, it just needs an additional sanity check build in. If you need more info, just ask.

2021-08-04 16:17 UTC, lifehackerhansol commented
I haven't had time to do more commits. It's been on my mind for quite a while though, I might revert the changes again. 

I have absolutely no idea where I'd place the checks, though.

2021-08-04 16:48 UTC, d0k3 commented
It belongs right below where you made the data_size change. data_size + 32 may, in some rare cases, exceed cart_size, causing a lot of trouble. You just make sure data_size is never more than cart_size.

2021-08-04 18:24 UTC, lifehackerhansol commented
Isn't that check already done in https://github.com/d0k3/GodMode9/blob/4dc96d37e84e341cf8e0aecc1a26c1e0f84b4004/arm9/source/gamecart/gamecart.c#L274 ? Or do you want more safety checks?

2021-08-05 15:31 UTC, d0k3 requested changes
That check is wrong, but, guess what, you can remove it. We already got the sanity check, a few lines below:
`if (cdata->data_size > cdata->cart_size) return 1;` (which you already noticed, I see).

Anyways, remove the check. And yes, I'm fully aware we're then back at the first version of this pull request. And yes, my fault for not paying attention and causing all the confusion. Sorry :^)

Once you done that, could you provide a testing built in the GitHub issue? I'll merge it if it is tested okay then.

2021-08-05 20:12 UTC, lifehackerhansol commented
Kind of off-topic, but I noticed local builds seem to produce smaller binaries... but I assume the end result would be the same, so.

2021-08-19 19:32 UTC, d0k3 commented
Merged, thank you!

2021-08-19 19:32 UTC, closed without merging